### ISSUE TITLE
Sort output in ping_show command

### ISSUE THREAD

**Issue by ghost** [Cuttlerat/prolog_bot#1]
I need sorting in output of `/ping_show` command by alphabet and timestamp.

Current output:
```
ждун
ждуна
жиробас
жиробаса
лалка
лалку
тостер
жирный
круглый
🤔
🧐
тостера
```
should be 
```
ждун
ждуна
жирный
жиробас
жиробаса
круглый
лалка
лалку
тостер
тостера
🤔
🧐
```

**Comment by R1AACR** [comment]
Sorting by creation time is the most suitable for this. Won't fix.
