### ISSUE TITLE
[BUG] Zero-Width Space character after command 

### ISSUE THREAD

**Issue by CrownBerry** [Cuttlerat/prolog_bot#7]
**Describe the bug**
Commands does not work with zero-width space character in the end of the command.

**To Reproduce**
1. Type `/set_me`
2. Past ZWS character
3. Type ` Test name`
4. Send message

**Expected behavior**
Got reply from bot: "Now I'll call you Test name"

**Screenshots**
![image](https://user-images.githubusercontent.com/8062502/64540452-8b3dad00-d320-11e9-8a67-d410b76e7a05.png)

**Comment by R1AACR** [comment]
It's not an issue, I don't think this is even should work
